/**
 * @packageDocumentation
 * @module api.functional.bbs.articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IBbsArticle } from "../../../structures/bbs/IBbsArticle";
import type { IPage } from "../../../structures/common/IPage";

export * as comments from "./comments";

/**
 * List up all summarized articles.
 *
 * List up all summarized articles with pagination and searching options.
 *
 * @param input Request info of pagination and searching options.
 * @returns Paginated summarized articles.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticlesController.index
 * @path PATCH /bbs/articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  input: IBbsArticle.IRequest,
): Promise<index.Output> {
  return !!connection.simulate
    ? index.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          template: index.METADATA.path,
          path: index.path(),
        },
        input,
      );
}
export namespace index {
  export type Input = IBbsArticle.IRequest;
  export type Output = IPage<IBbsArticle.ISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/bbs/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/bbs/articles";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IPage<IBbsArticle.ISummary> =>
    typia.random<IPage<IBbsArticle.ISummary>>(g);
  export const simulate = (
    connection: IConnection,
    input: IBbsArticle.IRequest,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * List up all abridged articles.
 *
 * List up all abridged articles with pagination and searching options.
 *
 * @param input Request info of pagination and searching options.
 * @returns Paginated abridged articles.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticlesController.abridges
 * @path PATCH /bbs/articles/abridges
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function abridges(
  connection: IConnection,
  input: IBbsArticle.IRequest,
): Promise<abridges.Output> {
  return !!connection.simulate
    ? abridges.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...abridges.METADATA,
          template: abridges.METADATA.path,
          path: abridges.path(),
        },
        input,
      );
}
export namespace abridges {
  export type Input = IBbsArticle.IRequest;
  export type Output = IPage<IBbsArticle.IAbridge>;

  export const METADATA = {
    method: "PATCH",
    path: "/bbs/articles/abridges",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/bbs/articles/abridges";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IPage<IBbsArticle.IAbridge> =>
    typia.random<IPage<IBbsArticle.IAbridge>>(g);
  export const simulate = (
    connection: IConnection,
    input: IBbsArticle.IRequest,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Read individual article.
 *
 * Reads an article with its every {@link IBbsArticle.ISnapshot snapshots}.
 *
 * @param id Target article's {@link IBbsArticle.id }
 * @returns Article information
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticlesController.at
 * @path GET /bbs/articles/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  id: string & Format<"uuid">,
): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection, id)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(id),
      });
}
export namespace at {
  export type Output = IBbsArticle;

  export const METADATA = {
    method: "GET",
    path: "/bbs/articles/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/bbs/articles/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): IBbsArticle =>
    typia.random<IBbsArticle>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Create a new article.
 *
 * Create a new article with its first {@link IBbsArticle.ISnapshot snapshot}.
 *
 * @param input Article information to create.
 * @returns Newly created article.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticlesController.create
 * @path POST /bbs/articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  input: IBbsArticle.ICreate,
): Promise<create.Output> {
  return !!connection.simulate
    ? create.simulate(connection, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(),
        },
        input,
      );
}
export namespace create {
  export type Input = IBbsArticle.ICreate;
  export type Output = IBbsArticle;

  export const METADATA = {
    method: "POST",
    path: "/bbs/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/bbs/articles";
  export const random = (g?: Partial<typia.IRandomGenerator>): IBbsArticle =>
    typia.random<IBbsArticle>(g);
  export const simulate = (
    connection: IConnection,
    input: IBbsArticle.ICreate,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Update an article.
 *
 * Accumulate a new {@link IBbsArticle.ISnapshot snapshot} record to the article.
 *
 * @param id Target article's {@link IBbsArticle.id }
 * @param input Article information to update.
 * @returns Newly accumulated snapshot information.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticlesController.update
 * @path PUT /bbs/articles/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string & Format<"uuid">,
  input: IBbsArticle.IUpdate,
): Promise<update.Output> {
  return !!connection.simulate
    ? update.simulate(connection, id, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(id),
        },
        input,
      );
}
export namespace update {
  export type Input = IBbsArticle.IUpdate;
  export type Output = IBbsArticle.ISnapshot;

  export const METADATA = {
    method: "PUT",
    path: "/bbs/articles/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/bbs/articles/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): IBbsArticle.ISnapshot => typia.random<IBbsArticle.ISnapshot>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
    input: IBbsArticle.IUpdate,
  ): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Erase an article.
 *
 * Performs soft deletion to the article.
 *
 * @param id Target article's {@link IBbsArticle.id }
 * @param input Password of the article.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticlesController.erase
 * @path DELETE /bbs/articles/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  id: string & Format<"uuid">,
  input: IBbsArticle.IErase,
): Promise<void> {
  return !!connection.simulate
    ? erase.simulate(connection, id, input)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          template: erase.METADATA.path,
          path: erase.path(id),
        },
        input,
      );
}
export namespace erase {
  export type Input = IBbsArticle.IErase;

  export const METADATA = {
    method: "DELETE",
    path: "/bbs/articles/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string & Format<"uuid">) =>
    `/bbs/articles/${encodeURIComponent(id?.toString() ?? "null")}`;
  export const random = (g?: Partial<typia.IRandomGenerator>): void =>
    typia.random<void>(g);
  export const simulate = (
    connection: IConnection,
    id: string & Format<"uuid">,
    input: IBbsArticle.IErase,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(id),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(id));
    assert.body(() => typia.assert(input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
