/**
 * @packageDocumentation
 * @module api.functional.bbs.articles.comments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { tags } from "typia";
import typia from "typia";

import type { IBbsArticleComment } from "../../../../structures/bbs/IBbsArticleComment";
import type { IPage } from "../../../../structures/common/IPage";

/**
 * List up all summarized comments.
 *
 * List up all summarized comments with pagination and searching options.
 *
 * @param props.body Request info of pagination and searching options.
 * @returns Paginated summarized comments.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticleCommentsController.index
 * @path PATCH /bbs/articles/:articleId/comments
 * @accessor api.functional.bbs.articles.comments.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Output> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          template: index.METADATA.path,
          path: index.path(props),
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    articleId: string & tags.Format<"uuid">;

    /**
     * Request info of pagination and searching options.
     */
    body: Body;
  };
  export type Body = IBbsArticleComment.IRequest;
  export type Output = IPage<IBbsArticleComment>;

  export const METADATA = {
    method: "PATCH",
    path: "/bbs/articles/:articleId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.articleId?.toString() ?? "null")}/comments`;
  export const random = (): IPage<IBbsArticleComment> =>
    typia.random<IPage<IBbsArticleComment>>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("articleId")(() => typia.assert(props.articleId));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}

/**
 * Read individual comment.
 *
 * Reads a comment with its every {@link IBbsArticleComment.ISnapshot snapshots}.
 *
 * @param props.articleId Belonged article's {@link IBbsArticle.id }
 * @param props.id Target comment's {@link IBbsArticleComment.id }
 * @returns Comment information
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticleCommentsController.at
 * @path GET /bbs/articles/:articleId/comments/:id
 * @accessor api.functional.bbs.articles.comments.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Output> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(props),
      });
}
export namespace at {
  export type Props = {
    /**
     * Belonged article's
     */
    articleId: string & tags.Format<"uuid">;

    /**
     * Target comment's
     */
    id: string & tags.Format<"uuid">;
  };
  export type Output = IBbsArticleComment;

  export const METADATA = {
    method: "GET",
    path: "/bbs/articles/:articleId/comments/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/bbs/articles/${encodeURIComponent(props.articleId?.toString() ?? "null")}/comments/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): IBbsArticleComment =>
    typia.random<IBbsArticleComment>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("articleId")(() => typia.assert(props.articleId));
    assert.param("id")(() => typia.assert(props.id));
    return random();
  };
}

/**
 * Create a new comment.
 *
 * Create a new comment with its first {@link IBbsArticleComment.ISnapshot snapshot}.
 *
 * @param props.articleId Belonged article's {@link IBbsArticle.id }
 * @param props.body Comment information to create.
 * @returns Newly created comment.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticleCommentsController.create
 * @path POST /bbs/articles/:articleId/comments
 * @accessor api.functional.bbs.articles.comments.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Output> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          template: create.METADATA.path,
          path: create.path(props),
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /**
     * Belonged article's
     */
    articleId: string & tags.Format<"uuid">;

    /**
     * Comment information to create.
     */
    body: Body;
  };
  export type Body = IBbsArticleComment.ICreate;
  export type Output = IBbsArticleComment;

  export const METADATA = {
    method: "POST",
    path: "/bbs/articles/:articleId/comments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.articleId?.toString() ?? "null")}/comments`;
  export const random = (): IBbsArticleComment =>
    typia.random<IBbsArticleComment>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("articleId")(() => typia.assert(props.articleId));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}

/**
 * Update a comment.
 *
 * Accumulate a new {@link IBbsArticleComment.ISnapshot snapshot} record to the comment.
 *
 * @param props.articleId Belonged article's {@link IBbsArticle.id }
 * @param props.id Target comment's {@link IBbsArticleComment.id }
 * @param props.body Comment information to update.
 * @returns Newly accumulated snapshot information.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticleCommentsController.update
 * @path PUT /bbs/articles/:articleId/comments/:id
 * @accessor api.functional.bbs.articles.comments.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Output> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          template: update.METADATA.path,
          path: update.path(props),
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /**
     * Belonged article's
     */
    articleId: string & tags.Format<"uuid">;

    /**
     * Target comment's
     */
    id: string & tags.Format<"uuid">;

    /**
     * Comment information to update.
     */
    body: Body;
  };
  export type Body = IBbsArticleComment.IUpdate;
  export type Output = IBbsArticleComment.ISnapshot;

  export const METADATA = {
    method: "PUT",
    path: "/bbs/articles/:articleId/comments/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.articleId?.toString() ?? "null")}/comments/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): IBbsArticleComment.ISnapshot =>
    typia.random<IBbsArticleComment.ISnapshot>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("articleId")(() => typia.assert(props.articleId));
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}

/**
 * Erase a comment.
 *
 * Performs soft deletion to the comment.
 *
 * @param props.articleId Belonged article's {@link IBbsArticle.id }
 * @param props.id Target comment's {@link IBbsArticleComment.id }
 * @param props.body Password of the comment.
 * @tag BBS
 * @author Samchon
 *
 * @controller BbsArticleCommentsController.erase
 * @path DELETE /bbs/articles/:articleId/comments/:id
 * @accessor api.functional.bbs.articles.comments.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          template: erase.METADATA.path,
          path: erase.path(props),
        },
        props.body,
      );
}
export namespace erase {
  export type Props = {
    /**
     * Belonged article's
     */
    articleId: string & tags.Format<"uuid">;

    /**
     * Target comment's
     */
    id: string & tags.Format<"uuid">;

    /**
     * Password of the comment.
     */
    body: Body;
  };
  export type Body = IBbsArticleComment.IErase;

  export const METADATA = {
    method: "DELETE",
    path: "/bbs/articles/:articleId/comments/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/bbs/articles/${encodeURIComponent(props.articleId?.toString() ?? "null")}/comments/${encodeURIComponent(props.id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("articleId")(() => typia.assert(props.articleId));
    assert.param("id")(() => typia.assert(props.id));
    assert.body(() => typia.assert(props.body));
    return random();
  };
}
