name: build
on:
  pull_request:
    paths:
      - "prisma/**"
      - "src/**"
      - "test/**"
      - "package.json"

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Backend-Server
        run: pnpm install

      - name: Compile Backend-Server
        run: npm run build

      - name: Validate through EsLint
        run: npm run eslint

      - name: Test Backend-Server
        run: npm run test -- --reset true --simultaneous 16
